apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-appointments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-appointments
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: courses-appointments
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: courses-appointments
        image: sgse2021cr.azurecr.io/ms_courses_appointments:latest
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: courses-appointments
spec:
  ports:
  - port: 8080
  selector:
    app: courses-appointments
