apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-appointments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-appointments
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: courses-appointments
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: courses-appointments
        image: sgse2021cr.azurecr.io/ms_courses_appointments:latest
        env: 
        - name: DATABASE_DNS
          valueFrom: 
            secretKeyRef: 
              name: coursesdb-secret
              key: dns
        - name: DATABASE_USER
          valueFrom: 
            secretKeyRef: 
              name: coursesdb-secret
              key: user
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: coursesdb-secret
              key: password
        - name: DATABASE_ADMIN_PW
          valueFrom: 
            secretKeyRef: 
              name: coursesdb-secret
              key: admin_pw
        - name: DATABASE_NAME
          valueFrom: 
            secretKeyRef: 
              name: coursesdb-secret
              key: database
        - name: DATABASE_PORT
          valueFrom: 
            secretKeyRef: 
              name: coursesdb-secret
              key: port
        - name: RABBIT_MQ
          valueFrom: 
            secretKeyRef: 
              name: rabbitmq-secret
              key: url
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: courses-appointments
spec:
  ports:
  - port: 8080
  selector:
    app: courses-appointments
