apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-appointments-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-appointments-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: courses-appointments-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: courses-appointments-frontend
        image: sgse2021cr.azurecr.io/ms_courses_appointments_frontend:latest
        ports:
        - containerPort: 80
---   
apiVersion: v1
kind: Service
metadata:
  name: courses-appointments-frontend
spec:
  ports:
  - port: 80
  selector:
    app: courses-appointments-frontend
